Presentation/Controllers/BoSuuTapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure;

namespace Presentation.Controllers
{
    public class BoSuuTapController : Controller
    {
        private readonly MeMoMay _context;

        public BoSuuTapController(MeMoMay context)
        {
            _context = context;
        }

        // GET: BoSuuTap
        public async Task<IActionResult> Index()
        {
            return View(await _context.BoSuuTaps.ToListAsync());
        }

        // GET: BoSuuTap/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boSuuTap = await _context.BoSuuTaps
                .FirstOrDefaultAsync(m => m.MaBoSuuTap == id);
            if (boSuuTap == null)
            {
                return NotFound();
            }

            return View(boSuuTap);
        }

        // GET: BoSuuTap/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BoSuuTap/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaBoSuuTap,TenBoSuuTap")] BoSuuTap boSuuTap)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boSuuTap);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boSuuTap);
        }

        // GET: BoSuuTap/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boSuuTap = await _context.BoSuuTaps.FindAsync(id);
            if (boSuuTap == null)
            {
                return NotFound();
            }
            return View(boSuuTap);
        }

        // POST: BoSuuTap/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaBoSuuTap,TenBoSuuTap")] BoSuuTap boSuuTap)
        {
            if (id != boSuuTap.MaBoSuuTap)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boSuuTap);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoSuuTapExists(boSuuTap.MaBoSuuTap))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boSuuTap);
        }

        // GET: BoSuuTap/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boSuuTap = await _context.BoSuuTaps
                .FirstOrDefaultAsync(m => m.MaBoSuuTap == id);
            if (boSuuTap == null)
            {
                return NotFound();
            }

            return View(boSuuTap);
        }

        // POST: BoSuuTap/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boSuuTap = await _context.BoSuuTaps.FindAsync(id);
            _context.BoSuuTaps.Remove(boSuuTap);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoSuuTapExists(int id)
        {
            return _context.BoSuuTaps.Any(e => e.MaBoSuuTap == id);
        }
    }
}

Presentation/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure;
using ApplicationCore.Interfaces.IServices;
using Presentation.ServiceViews;
using Microsoft.AspNetCore.Http;
using ApplicationCore.ViewModels;

namespace Presentation.Controllers
{
    public class KhachHangController : Controller
    {
        private readonly MeMoMay _context;
        private readonly IKhachHangService _service;
        private readonly KhachHangServiceView _serviceV;

        public KhachHangController(MeMoMay context,IKhachHangService service,KhachHangServiceView serviceView)
        {
            _context = context;
            _service = service;
            _serviceV = serviceView;
        }

        // GET: KhachHang
        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("Username") != null )
            {
                return View(_serviceV.GetHangIndexVM(null,1));
            }
            else
            {
                return RedirectToAction("Index", "Account");
            }
        }
        [HttpGet]
        public IActionResult Index(string CurrentFilter, int pageIndex = 1)
        {
            //AddViewData
            ViewData["CurrentFilter"] = CurrentFilter;
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Index", "Account");
            }
            else
            {
                KhachHangIndexVM vm = _serviceV.GetHangIndexVM(CurrentFilter, pageIndex);
                return View(vm);
            }
        }

        // GET: KhachHang/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // GET: KhachHang/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: KhachHang/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaKhachHang,TenKhachHang,SDT,DiaChi,LienHe")] KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                if(_serviceV.CheckPhoneNumberExist(khachHang.SDT) )
                {
                _context.Add(khachHang);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewData["ExistPhoneNumber"] = "Số điện thoại đã được đăng ký";
                    return View();
                }
            }
            return View(khachHang);
        }

        // GET: KhachHang/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }
            return View(khachHang);
        }

        // POST: KhachHang/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaKhachHang,TenKhachHang,SDT,DiaChi,LienHe")] KhachHang khachHang)
        {
            if (id != khachHang.MaKhachHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(khachHang);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.MaKhachHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(khachHang);
        }

        // GET: KhachHang/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var khachHang = await _context.KhachHangs
                .FirstOrDefaultAsync(m => m.MaKhachHang == id);
            if (khachHang == null)
            {
                return NotFound();
            }

            return View(khachHang);
        }

        // POST: KhachHang/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var khachHang = await _context.KhachHangs.FindAsync(id);
            _context.KhachHangs.Remove(khachHang);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KhachHangExists(int id)
        {
            return _context.KhachHangs.Any(e => e.MaKhachHang == id);
        }
    }
}

Presentation/Controllers/NhanVienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure;
using ApplicationCore.Interfaces.IServices;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;

namespace Presentation.Controllers
{
    public class NhanVienController : Controller
    {
        private readonly INhanVienService _serviceNV;
        public NhanVienController(INhanVienService service)
        {
            _serviceNV = service;
        }
        public IActionResult Index()
        {
            if(HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Index", "Account");
            }
            else
            {
                if(HttpContext.Session.GetString("VaiTro") == "SuperAdmin")
                {
                    return View(_serviceNV.Getall());
                }
                else if(HttpContext.Session.GetString("VaiTro") == "Admin")
                {
                    return View(_serviceNV.Getall().Where(m => m.VaiTro == "Member"));
                }
                else
                {
                    HttpContext.Session.Remove("Username");
                    return RedirectToAction("Index", "Account");
                }
            }
        }
        [HttpPost]
        public bool ChangeStatus(int id, int status)
        {
            if (HttpContext.Session.GetString("Username") == null)
                return false;
            NhanVien nv = _serviceNV.GetById(id);
            nv.TrangThai = status;
            _serviceNV.Update(nv);
            return true;
        }
        [HttpPost]
        public bool ChangeRole(int id, string role)
        {
            if (HttpContext.Session.GetString("Username") == null)
                return false;
            NhanVien nv = _serviceNV.GetById(id);
            nv.VaiTro = role;
            _serviceNV.Update(nv);
            return true;
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Index", "Account");
            }
            else
            {
                return View(_serviceNV.GetById(id));
            }
        }
        [HttpPost]
        public IActionResult Edit(NhanVien NhanVien,string MatKhauXacNhan,string MatKhau)
        {
            if (HttpContext.Session.GetString("Username") == null)
            {
                return RedirectToAction("Index", "Account");
            }
            else
            {
                if(MatKhau != MatKhauXacNhan)
                {
                    ViewData["LoiMatKhau"] = "Mật khẩu không khớp";
                    return View(_serviceNV.GetById(NhanVien.MaNhanVien));
                }
                else
                {
                    NhanVien nv = _serviceNV.GetById(NhanVien.MaNhanVien);
                    nv.HoTen = NhanVien.HoTen;
                    nv.SDT = NhanVien.SDT;
                    nv.GioiTinh = NhanVien.GioiTinh;
                    using(MD5 md5hash = MD5.Create())
                    {
                        nv.MatKhau = _serviceNV.GetMd5hash(md5hash, MatKhauXacNhan);
                    }
                    _serviceNV.Update(nv);
                    ViewData["ThongBaoThanhCong"] = "Cập nhật thông tin thành công";
                    return View(_serviceNV.GetById(NhanVien.MaNhanVien));
                }
                
            }
        }
    }
}

Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link href="~/img/logo/logo3.png" rel="icon">
  <title>MeMoMay</title>
  <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
  <link href="~/css/ruang-admin.css" rel="stylesheet">
  <link rel="stylesheet" href="~/assets/css/animate-3.7.0.css">
  <link rel="stylesheet" href="~/assets/css/font-awesome-4.7.0.min.css">
  <link rel="stylesheet" href="~/assets/css/bootstrap-4.1.3.min.css">
  <link rel="stylesheet" href="~/assets/css/owl-carousel.min.css">
  <link rel="stylesheet" href="~/assets/css/jquery.datetimepicker.min.css">
  <link rel="stylesheet" href="~/assets/css/style.css">
  @* <script src="~/assets/js/vendor/jquery-2.2.4.min.js"></script> *@
	<script src="~/assets/js/vendor/bootstrap-4.1.3.min.js"></script>
  @* <script src="~/assets/js/vendor/wow.min.js"></script> *@
  @* <script src="~/assets/js/vendor/owl-carousel.min.js"></script> *@
  @* <script src="~/assets/js/vendor/jquery.datetimepicker.full.min.js"></script> *@
  @* <script src="~/assets/js/main.js"></script> *@
  @* <script type="text/javascript" src="~/js/jquery-3.4.1.min.js"></script> *@
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>

<body id="page-top">
  <div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
      <a class="sidebar-brand d-flex align-items-center justify-content-center" style="height: 70" asp-controller="Home" asp-action="Index">
        <div class="sidebar-brand-icon">
          <img src="~/img/logo/logo3.jpg" style="height: auto">
        </div>
        <div class="sidebar-brand-text mx-3">Mẹ Mơ May</div>
      </a>
      <div class="sidebar-heading" style="margin-top: 10px;">
        Menu
      </div>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="DonHang">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý đơn hàng</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="SanPham">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý sản phẩm</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="BoSuuTap">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý bộ sưu tập</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="KhachHang">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý khách hàng</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="ThongTinNhapHang">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý nhập hàng</span>
        </a>
      </li>
      @if(@Context.Session.GetString("VaiTro") != "Member" )
      {
        <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="NhanVien">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Quản lý nhân sự</span>
        </a>  
        </li>
        <li class="nav-item">
        <a class="nav-link" asp-action="Index" asp-controller="ThongKe">
          <i class="fab fa-fw fa-wpforms"></i>
          <span>Thống kê</span>
        </a>
        </li>
      }
      
      <hr class="sidebar-divider">
      <div class="version" >1.0.0</div>
    </ul>
    
    <!-- Sidebar -->
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
            <!-- TopBar -->
        <nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
          <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <img class="img-profile rounded-circle" src="~/img/boy.png" style="max-width: 60px">
                <span class="ml-2 d-none d-lg-inline text-white small">@Context.Session.GetString("TenNhanVien")</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" asp-action="Edit" asp-controller="NhanVien" asp-route-id="@Context.Session.GetString("MaNhanVien")">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a asp-controller="Account" asp-action="Logout" class="dropdown-item">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400">Đăng xuất</i>
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- Topbar -->
            @RenderBody()
      </div>
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span style="color:black">copyright &copy; 2019 - developed by
              <b><a href="https://www.facebook.com/profile.php?id=100009073476722" target="_blank">Minh Hien</a></b>
            </span>
          </div>
        </div>
      </footer>
      <!-- Footer -->
    </div>
  </div>
</div>
</div>
  <!-- Scroll to top -->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
  @RenderSection("Scripts", required: false)
  @* <script src="~/vendor/jquery/jquery.min.js"></script> *@
  <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  @* <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script> *@
  <script src="~/js/ruang-admin.min.js"></script>
  <script src="~/vendor/chart.js/Chart.min.js"></script>
  <script src="~/js/demo/chart-area-demo.js"></script>  
  <script src="~/js/Controller/donHangController.js"></script>
  <script src="~/js/Controller/nhapHangController.js"></script>
  <script >
    //drop down menu 
    $(document).ready(function() {
     $(".dropdown-toggle").dropdown();
    });
  </script>
  @RenderSection("jsFooter", required: false)
</body>

</html>